# Generated by Django 3.2.5 on 2021-07-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SlidePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('index', models.IntegerField()),
                ('slide_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slidetype')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translator.word')),
            ],
        ),
    ]
