# Generated by Django 3.2.5 on 2021-08-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DecorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerDate', models.DateTimeField()),
                ('lastChangeDate', models.DateTimeField()),
                ('orderStatus', models.CharField(max_length=50)),
                ('income', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('profit', models.DecimalField(blank=True, decimal_places=10, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.ordercategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DecorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.decorcategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.customer')),
            ],
        ),
    ]
