# Generated by Django 3.2.5 on 2021-08-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorbusiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DecorSample',
        ),
    ]
