# Generated by Django 3.2.5 on 2021-08-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decorbusiness', '0002_auto_20210830_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.decorcategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.customer')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.maincategory')),
            ],
        ),
    ]
