# Generated by Django 3.2.5 on 2021-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210830_1054'),
        ('decorbusiness', '0003_decorsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorsample',
            name='images',
            field=models.ManyToManyField(to='main.Images'),
        ),
    ]
