# Generated by Django 3.2.5 on 2021-09-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210830_1054'),
        ('decorbusiness', '0005_delete_decorsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('addedDate', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.decorcategory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.customer')),
                ('images', models.ManyToManyField(to='main.Images')),
                ('mainCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decorbusiness.maincategory')),
            ],
        ),
    ]
