# Generated by Django 3.2.5 on 2021-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorbusiness', '0006_decorsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorsample',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
